name: Download and Compress Alist with UPX
on:
  workflow_dispatch:  # 手动触发
    inputs:
      upx_args:
        description: 'UPX compression parameters (e.g. -9 --best)'
        required: false
        default: '--best'

env:
  UPX_DOWNLOAD_NAME: "upx-${{ github.event.inputs.upx_version || 'latest' }}-amd64_linux.tar.xz"

jobs:
  compress:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Get Alist release info
        id: get_alist
        run: |
          RELEASE_JSON=$(curl -sL "https://api.github.com/repos/AlistGo/alist/releases/latest")
          VERSION=$(jq -r '.tag_name | ltrimstr("v")' <<< "$RELEASE_JSON")
          URL=$(jq -r '.assets[] | select(.name == "alist-linux-musl-arm64.tar.gz").browser_download_url' <<< "$RELEASE_JSON")
          
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "url=$URL" >> $GITHUB_OUTPUT

      - name: Download and extract Alist
        run: |
          curl -L -o alist.tar.gz "${{ steps.get_alist.outputs.url }}"
          tar zxvf alist.tar.gz
          rm alist.tar.gz
          chmod +x alist

      - name: Get UPX latest version
        id: upx_info
        run: |
          UPX_INFO=$(curl -sL "https://api.github.com/repos/upx/upx/releases/latest")
          UPX_VERSION=$(echo "$UPX_INFO" | jq -r '.tag_name | ltrimstr("v")')
          UPX_DOWNLOAD_URL=$(echo "$UPX_INFO" | jq -r '.assets[] | select(.name | test(".*amd64_linux.tar.xz$")) | .browser_download_url')
          
          echo "upx_version=$UPX_VERSION" >> $GITHUB_OUTPUT
          echo "upx_download_url=$UPX_DOWNLOAD_URL" >> $GITHUB_OUTPUT

       - name: Download and setup UPX
        run: |
          set -ex
          curl -L -o upx.tar.xz "${{ steps.upx_info.outputs.upx_download_url }}"
          tar -xJOf upx.tar.xz "upx-${{ steps.upx_info.outputs.upx_version }}-amd64_linux/upx" > ./upx
          chmod +x ./upx

      - name: Compress with UPX
        run: |
          set -ex
          ./upx ${{ github.event.inputs.upx_args }} ./alist

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: alist_${{ steps.get_alist.outputs.version }}_upx
          path: alist