name: Build UPX-Compressed Alist
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Get Latest Release Info
      id: get_release
      uses: actions/github-script@v5
      with:
        script: |
          const response = await github.rest.repos.getLatestRelease({
            owner: 'AlistGo',  // 关键修正点
            repo: 'alist'
          });
          
          // 精确匹配 ARM64 压缩包
          const asset = response.data.assets.find(a => 
            a.name === 'alist-linux-arm64.tar.gz' // 严格名称匹配
          );
          
          if (!asset) throw new Error('ARM64 asset not found');
          return {
            url: asset.browser_download_url,
            version: response.data.tag_name.replace(/^v/, '') // 去除版本号前的v
          };

    - name: Download and Validate
      run: |
        # 下载指定版本
        curl -L "${{ steps.get_release.outputs.result.url }}" \
          -o alist.tar.gz
        
        # 验证文件完整性
        tar -ztvf alist.tar.gz | grep -q 'alist$' || (echo "::error::Invalid file structure"; exit 1)
        
        # 解压文件
        tar -xzf alist.tar.gz
        chmod +x alist

    - name: UPX Compress
      uses: crazy-max/ghaction-upx@v3
      with:
        files: ./alist
        args: --best --lzma

    - name: Package Artifact
      run: |
        # 重命名文件包含版本号
        COMPRESSED_NAME="alist-upx_${{ steps.get_release.outputs.result.version }}_arm64"
        mv alist $COMPRESSED_NAME
        
        # 生成校验文件
        sha256sum $COMPRESSED_NAME > $COMPRESSED_NAME.sha256

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: alist-upx-arm64
        path: |
          ./alist-upx_*_arm64
          ./*.sha256
