name: Build UPX-Compressed Alist
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # 允许上传 Artifact
      actions: read    # 允许跨仓库访问
    steps:
    - name: Checkout current repo
      uses: actions/checkout@v3
      # 移除非必要的 repository 参数，默认使用当前仓库

    - name: Get Alist Release Info
      id: get_release
      uses: actions/github-script@v5
      with:
        script: |
          const response = await github.rest.repos.getLatestRelease({
            owner: 'AlistGo',  # 关键修正
            repo: 'alist'      # 指定正确仓库
          });
          const asset = response.data.assets.find(a => 
            a.name === 'alist-linux-arm64.tar.gz'
          );
          if (!asset) throw new Error('ARM64 asset not found');
          return { 
            url: asset.browser_download_url,
            version: response.data.tag_name 
          };

    - name: Download and Extract
      run: |
        curl -L "${{ steps.get_release.outputs.result.url }}" -o alist.tar.gz
        tar -xzf alist.tar.gz
        chmod +x alist

    - name: UPX Compress
      uses: crazy-max/ghaction-upx@v3
      with:
        files: ./alist
        args: --best

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: alist-upx-arm64
        path: ./alist
