name: Custom File Download and Compress with UPX
on:
  workflow_dispatch:   # 手动触发
    inputs:
      file_url:
        description: 'url'
        required: true
      save_path:
        description: '文件保存路径（默认：./）'
        required: false
        default: './'
      upx_args:
        description: 'upx_args'
        required: false
        default: '--best'

env:
  UPX_DOWNLOAD_NAME: "upx-${{ github.event.inputs.upx_version || 'latest' }}-amd64_linux.tar.xz"

jobs:
  compress:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Environment
        run: |
          mkdir -p "${{ github.event.inputs.save_path }}"
          echo "WORKDIR=$(pwd)" >> $GITHUB_ENV
          
      - name: Get UPX latest version
        id: upx_info
        run: |
          UPX_INFO=$(curl -sL "https://api.github.com/repos/upx/upx/releases/latest")
          UPX_VERSION=$(echo "$UPX_INFO" | jq -r '.tag_name | ltrimstr("v")')
          UPX_DOWNLOAD_URL=$(echo "$UPX_INFO" | jq -r '.assets[] | select(.name | test(".*amd64_linux.tar.xz$")) | .browser_download_url')
      
      - name: Set up jq
        run: sudo apt-get update && sudo apt-get install -y jq

     
      - name: Download File
        run: |
          FILENAME=$(basename "${{ github.event.inputs.file_url }}")
          curl -L -o "${FILENAME}" "${{ github.event.inputs.file_url }}"
          echo "DOWNLOADED_FILE=${FILENAME}" >> $GITHUB_ENV


      - name: Download and setup UPX
        run: |
          set -ex
          curl -L -o upx.tar.xz "${{ steps.upx_info.outputs.upx_download_url }}"
          tar -xJOf upx.tar.xz "upx-${{ steps.upx_info.outputs.upx_version }}-amd64_linux/upx" > ./upx
          chmod +x ./upx
          
      - name: Compress with UPX
        run: |
          chmod +x "${{ env.DOWNLOADED_FILE }}"
          upx ${{ github.event.inputs.upx_args }} "${{ env.DOWNLOADED_FILE }}"
          mv "${{ env.DOWNLOADED_FILE }}" "${{ github.event.inputs.save_path }}"

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: compressed_$(date +%s)
          path: "${{ github.event.inputs.save_path }}/${{ env.DOWNLOADED_FILE }}"
